# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marker_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='marker_data.proto',
  package='robotics.infrastructure.motion_capture.phasespace',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11marker_data.proto\x12\x31robotics.infrastructure.motion_capture.phasespace\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"6\n\x08Vector4f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\"+\n\x08Vector3f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\xb6\x01\n\nMarkerData\x12\x11\n\tmarker_id\x18\x02 \x01(\x05\x12P\n\x0bposition_mm\x18\x03 \x01(\x0b\x32;.robotics.infrastructure.motion_capture.phasespace.Vector3f\x12\x16\n\x0einternal_flags\x18\x04 \x01(\r\x12\x15\n\rinternal_time\x18\x05 \x01(\x03\x12\x14\n\x0cinternalcond\x18\x06 \x01(\x02\"\x81\x02\n\tRigidData\x12\x12\n\ntracker_id\x18\x02 \x01(\x05\x12P\n\x0bposition_mm\x18\x03 \x01(\x0b\x32;.robotics.infrastructure.motion_capture.phasespace.Vector3f\x12I\n\x04quat\x18\x07 \x01(\x0b\x32;.robotics.infrastructure.motion_capture.phasespace.Vector4f\x12\x16\n\x0einternal_flags\x18\x04 \x01(\r\x12\x15\n\rinternal_time\x18\x05 \x01(\x03\x12\x14\n\x0cinternalcond\x18\x06 \x01(\x02\"\x93\x02\n\x0bMarkersData\x12O\n\ttimestamp\x18\x01 \x01(\x0b\x32<.robotics.infrastructure.motion_capture.phasespace.Timestamp\x12N\n\x07markers\x18\x02 \x03(\x0b\x32=.robotics.infrastructure.motion_capture.phasespace.MarkerData\x12L\n\x06rigids\x18\x04 \x03(\x0b\x32<.robotics.infrastructure.motion_capture.phasespace.RigidData\x12\x15\n\rinternal_time\x18\x03 \x01(\x03\"\x15\n\x13MarkerTrackerParams2\xce\x02\n\rMarkerTracker\x12\x9a\x01\n\x0cTrackMarkers\x12\x46.robotics.infrastructure.motion_capture.phasespace.MarkerTrackerParams\x1a>.robotics.infrastructure.motion_capture.phasespace.MarkersData\"\x00\x30\x01\x12\x9f\x01\n\x13GetLatestMarkerData\x12\x46.robotics.infrastructure.motion_capture.phasespace.MarkerTrackerParams\x1a>.robotics.infrastructure.motion_capture.phasespace.MarkersData\"\x00\x62\x06proto3'
)




_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='robotics.infrastructure.motion_capture.phasespace.Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='robotics.infrastructure.motion_capture.phasespace.Timestamp.seconds', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nanos', full_name='robotics.infrastructure.motion_capture.phasespace.Timestamp.nanos', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=115,
)


_VECTOR4F = _descriptor.Descriptor(
  name='Vector4f',
  full_name='robotics.infrastructure.motion_capture.phasespace.Vector4f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='robotics.infrastructure.motion_capture.phasespace.Vector4f.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='robotics.infrastructure.motion_capture.phasespace.Vector4f.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='robotics.infrastructure.motion_capture.phasespace.Vector4f.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='w', full_name='robotics.infrastructure.motion_capture.phasespace.Vector4f.w', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=171,
)


_VECTOR3F = _descriptor.Descriptor(
  name='Vector3f',
  full_name='robotics.infrastructure.motion_capture.phasespace.Vector3f',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='robotics.infrastructure.motion_capture.phasespace.Vector3f.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='robotics.infrastructure.motion_capture.phasespace.Vector3f.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='robotics.infrastructure.motion_capture.phasespace.Vector3f.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=216,
)


_MARKERDATA = _descriptor.Descriptor(
  name='MarkerData',
  full_name='robotics.infrastructure.motion_capture.phasespace.MarkerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='marker_id', full_name='robotics.infrastructure.motion_capture.phasespace.MarkerData.marker_id', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_mm', full_name='robotics.infrastructure.motion_capture.phasespace.MarkerData.position_mm', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='internal_flags', full_name='robotics.infrastructure.motion_capture.phasespace.MarkerData.internal_flags', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='internal_time', full_name='robotics.infrastructure.motion_capture.phasespace.MarkerData.internal_time', index=3,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='internalcond', full_name='robotics.infrastructure.motion_capture.phasespace.MarkerData.internalcond', index=4,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=401,
)


_RIGIDDATA = _descriptor.Descriptor(
  name='RigidData',
  full_name='robotics.infrastructure.motion_capture.phasespace.RigidData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracker_id', full_name='robotics.infrastructure.motion_capture.phasespace.RigidData.tracker_id', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_mm', full_name='robotics.infrastructure.motion_capture.phasespace.RigidData.position_mm', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quat', full_name='robotics.infrastructure.motion_capture.phasespace.RigidData.quat', index=2,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='internal_flags', full_name='robotics.infrastructure.motion_capture.phasespace.RigidData.internal_flags', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='internal_time', full_name='robotics.infrastructure.motion_capture.phasespace.RigidData.internal_time', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='internalcond', full_name='robotics.infrastructure.motion_capture.phasespace.RigidData.internalcond', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=661,
)


_MARKERSDATA = _descriptor.Descriptor(
  name='MarkersData',
  full_name='robotics.infrastructure.motion_capture.phasespace.MarkersData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='robotics.infrastructure.motion_capture.phasespace.MarkersData.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='markers', full_name='robotics.infrastructure.motion_capture.phasespace.MarkersData.markers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rigids', full_name='robotics.infrastructure.motion_capture.phasespace.MarkersData.rigids', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='internal_time', full_name='robotics.infrastructure.motion_capture.phasespace.MarkersData.internal_time', index=3,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=664,
  serialized_end=939,
)


_MARKERTRACKERPARAMS = _descriptor.Descriptor(
  name='MarkerTrackerParams',
  full_name='robotics.infrastructure.motion_capture.phasespace.MarkerTrackerParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=941,
  serialized_end=962,
)

_MARKERDATA.fields_by_name['position_mm'].message_type = _VECTOR3F
_RIGIDDATA.fields_by_name['position_mm'].message_type = _VECTOR3F
_RIGIDDATA.fields_by_name['quat'].message_type = _VECTOR4F
_MARKERSDATA.fields_by_name['timestamp'].message_type = _TIMESTAMP
_MARKERSDATA.fields_by_name['markers'].message_type = _MARKERDATA
_MARKERSDATA.fields_by_name['rigids'].message_type = _RIGIDDATA
DESCRIPTOR.message_types_by_name['Timestamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['Vector4f'] = _VECTOR4F
DESCRIPTOR.message_types_by_name['Vector3f'] = _VECTOR3F
DESCRIPTOR.message_types_by_name['MarkerData'] = _MARKERDATA
DESCRIPTOR.message_types_by_name['RigidData'] = _RIGIDDATA
DESCRIPTOR.message_types_by_name['MarkersData'] = _MARKERSDATA
DESCRIPTOR.message_types_by_name['MarkerTrackerParams'] = _MARKERTRACKERPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'marker_data_pb2'
  # @@protoc_insertion_point(class_scope:robotics.infrastructure.motion_capture.phasespace.Timestamp)
  })
_sym_db.RegisterMessage(Timestamp)

Vector4f = _reflection.GeneratedProtocolMessageType('Vector4f', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR4F,
  '__module__' : 'marker_data_pb2'
  # @@protoc_insertion_point(class_scope:robotics.infrastructure.motion_capture.phasespace.Vector4f)
  })
_sym_db.RegisterMessage(Vector4f)

Vector3f = _reflection.GeneratedProtocolMessageType('Vector3f', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3F,
  '__module__' : 'marker_data_pb2'
  # @@protoc_insertion_point(class_scope:robotics.infrastructure.motion_capture.phasespace.Vector3f)
  })
_sym_db.RegisterMessage(Vector3f)

MarkerData = _reflection.GeneratedProtocolMessageType('MarkerData', (_message.Message,), {
  'DESCRIPTOR' : _MARKERDATA,
  '__module__' : 'marker_data_pb2'
  # @@protoc_insertion_point(class_scope:robotics.infrastructure.motion_capture.phasespace.MarkerData)
  })
_sym_db.RegisterMessage(MarkerData)

RigidData = _reflection.GeneratedProtocolMessageType('RigidData', (_message.Message,), {
  'DESCRIPTOR' : _RIGIDDATA,
  '__module__' : 'marker_data_pb2'
  # @@protoc_insertion_point(class_scope:robotics.infrastructure.motion_capture.phasespace.RigidData)
  })
_sym_db.RegisterMessage(RigidData)

MarkersData = _reflection.GeneratedProtocolMessageType('MarkersData', (_message.Message,), {
  'DESCRIPTOR' : _MARKERSDATA,
  '__module__' : 'marker_data_pb2'
  # @@protoc_insertion_point(class_scope:robotics.infrastructure.motion_capture.phasespace.MarkersData)
  })
_sym_db.RegisterMessage(MarkersData)

MarkerTrackerParams = _reflection.GeneratedProtocolMessageType('MarkerTrackerParams', (_message.Message,), {
  'DESCRIPTOR' : _MARKERTRACKERPARAMS,
  '__module__' : 'marker_data_pb2'
  # @@protoc_insertion_point(class_scope:robotics.infrastructure.motion_capture.phasespace.MarkerTrackerParams)
  })
_sym_db.RegisterMessage(MarkerTrackerParams)



_MARKERTRACKER = _descriptor.ServiceDescriptor(
  name='MarkerTracker',
  full_name='robotics.infrastructure.motion_capture.phasespace.MarkerTracker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=965,
  serialized_end=1299,
  methods=[
  _descriptor.MethodDescriptor(
    name='TrackMarkers',
    full_name='robotics.infrastructure.motion_capture.phasespace.MarkerTracker.TrackMarkers',
    index=0,
    containing_service=None,
    input_type=_MARKERTRACKERPARAMS,
    output_type=_MARKERSDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetLatestMarkerData',
    full_name='robotics.infrastructure.motion_capture.phasespace.MarkerTracker.GetLatestMarkerData',
    index=1,
    containing_service=None,
    input_type=_MARKERTRACKERPARAMS,
    output_type=_MARKERSDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MARKERTRACKER)

DESCRIPTOR.services_by_name['MarkerTracker'] = _MARKERTRACKER

# @@protoc_insertion_point(module_scope)
