# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from phasespace import marker_data_pb2 as marker__data__pb2


class MarkerTrackerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrackMarkers = channel.unary_stream(
                '/robotics.infrastructure.motion_capture.phasespace.MarkerTracker/TrackMarkers',
                request_serializer=marker__data__pb2.MarkerTrackerParams.SerializeToString,
                response_deserializer=marker__data__pb2.MarkersData.FromString,
                )
        self.GetLatestMarkerData = channel.unary_unary(
                '/robotics.infrastructure.motion_capture.phasespace.MarkerTracker/GetLatestMarkerData',
                request_serializer=marker__data__pb2.MarkerTrackerParams.SerializeToString,
                response_deserializer=marker__data__pb2.MarkersData.FromString,
                )


class MarkerTrackerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrackMarkers(self, request, context):
        """Streams MarkerData protobufs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestMarkerData(self, request, context):
        """Retrieves the latest singular instance of MarkerData.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarkerTrackerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrackMarkers': grpc.unary_stream_rpc_method_handler(
                    servicer.TrackMarkers,
                    request_deserializer=marker__data__pb2.MarkerTrackerParams.FromString,
                    response_serializer=marker__data__pb2.MarkersData.SerializeToString,
            ),
            'GetLatestMarkerData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestMarkerData,
                    request_deserializer=marker__data__pb2.MarkerTrackerParams.FromString,
                    response_serializer=marker__data__pb2.MarkersData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotics.infrastructure.motion_capture.phasespace.MarkerTracker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarkerTracker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrackMarkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/robotics.infrastructure.motion_capture.phasespace.MarkerTracker/TrackMarkers',
            marker__data__pb2.MarkerTrackerParams.SerializeToString,
            marker__data__pb2.MarkersData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLatestMarkerData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robotics.infrastructure.motion_capture.phasespace.MarkerTracker/GetLatestMarkerData',
            marker__data__pb2.MarkerTrackerParams.SerializeToString,
            marker__data__pb2.MarkersData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
